name: coronatrack
description: Covid-19 Updates
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

modules:
  androiX: true

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.png
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-Light.ttf
        - asset: assets/fonts/Prompt-SemiBold.ttf
        - asset: assets/fonts/Prompt-Medium.ttf
        - asset: assets/fonts/Prompt-Bold.ttf
        - asset: assets/fonts/Prompt-ExtraBold.ttf
        - asset: assets/fonts/Prompt-Black.ttf
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Regular.ttf
        - asset: assets/fonts/Dosis-Light.ttf
        - asset: assets/fonts/Dosis-ExtraLight.ttf
        - asset: assets/fonts/Dosis-SemiBold.ttf
        - asset: assets/fonts/Dosis-Medium.ttf
        - asset: assets/fonts/Dosis-Bold.ttf
        - asset: assets/fonts/Dosis-ExtraBold.ttf